### PR TITLE
Now handling expired access tokens properly.

### LINKED ISSUE #11: AuthPlugin doesn't handle expired tokens properly
If a stored access token from the authentication service is expired, it will be used anyway, causing `@adamite/relay-server` to disconnect the client.

## Steps to reproduce
1. Sign in to a web app connected to Adamite.
2. Inspect the stored access token in Local Storage, and then use jwt.io to change its `exp` property to an expired timestamp, like `1561700157`.
3. Refresh the page.

## Expected behavior
You should be signed out and your token should be removed from local storage, but otherwise you should be connected properly to the Adamite instance.

## Actual behavior
Your token is not removed from local storage, and you're unable to connect to the Adamite instance. Your instance will probably log something like this...
```
TokenExpiredError: jwt expired
```

### PR DESCRIPTION
**Pull request by JesseDunlap**
Resolves #11.

### CODE REVIEW

File: src/auth/AuthPlugin.ts [hunk 1]
```diff
@@ -111,13 +111,27 @@ class AuthPlugin extends EventEmitter implements AdamitePlugin {
     };
   }
 
+  private checkForExpiredToken() {
+    if (!this.currentToken) return;
+
+    const decodedToken = jwt.decode(this.currentToken) as AuthServiceToken;
+    if (!decodedToken) return undefined;
```
Comment (matthewlynn) [inline src/auth/AuthPlugin.ts]: Why return undefined here? Inconsistency!
